env: "dev" # local, dev, prod
storage_path: "./storage/storage.db"
database_url: "postgres://postgres:postgres@127.0.0.1:5432/url_shortener"
http_server:
  address: "localhost:8010"
  timeout: 4s
  idle_timeout: 60s
